"""update_embedding_provider_config_schema

Revision ID: 454138944efc
Revises: bdccb64add5b
Create Date: 2025-09-13 16:36:48.857876

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = '454138944efc'
down_revision = 'bdccb64add5b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if tables exist before dropping them
    connection = op.get_bind()
    
    # Check if embedding_provider_configs table exists
    result = connection.execute(text("""
        SELECT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE table_name = 'embedding_provider_configs'
        );
    """))
    table_exists = result.scalar()
    
    if table_exists:
        # Drop the existing table completely to start fresh
        # First drop the dependent table that has foreign key to embedding_provider_configs
        op.drop_table('workspace_embedding_settings')
        op.drop_table('embedding_provider_configs')
    
    # Check if enum type exists
    result = connection.execute(text("""
        SELECT EXISTS (
            SELECT FROM pg_type 
            WHERE typname = 'embeddingprovidertype'
        );
    """))
    enum_exists = result.scalar()
    
    if not enum_exists:
        # Create the new enum type with correct values
        op.execute(text("CREATE TYPE embeddingprovidertype AS ENUM ('OPENAI', 'AZURE', 'HUGGINGFACE', 'LOCAL')"))
    
    # Create the table with the correct schema (only if it doesn't exist)
    if not table_exists:
        op.create_table('embedding_provider_configs',
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('provider_type', sa.Enum('OPENAI', 'AZURE', 'HUGGINGFACE', 'LOCAL', name='embeddingprovidertype'), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('config', sa.JSON(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('version', sa.String(length=50), nullable=True),
        sa.Column('last_used', sa.String(), nullable=True),
        sa.Column('usage_count', sa.Integer(), nullable=False),
        sa.Column('average_latency', sa.Integer(), nullable=True),
        sa.Column('error_rate', sa.Integer(), nullable=True),
        sa.Column('total_tokens_processed', sa.Integer(), nullable=False),
        sa.Column('workspace_id', sa.String(), nullable=False),
        sa.Column('created_by', sa.String(), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('updated_by', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_embedding_provider_configs_created_by_users')),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_embedding_provider_configs_workspace_id_workspaces')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_embedding_provider_configs'))
    )
    
        # Create indexes for embedding_provider_configs
        op.create_index('idx_embedding_provider_configs_workspace_id', 'embedding_provider_configs', ['workspace_id'], unique=False)
        op.create_index('idx_embedding_provider_configs_provider_type', 'embedding_provider_configs', ['provider_type'], unique=False)
        op.create_index('idx_embedding_provider_configs_is_active', 'embedding_provider_configs', ['is_active'], unique=False)
        op.create_index('idx_embedding_provider_configs_created_at', 'embedding_provider_configs', ['created_at'], unique=False)
        op.create_index(op.f('ix_embedding_provider_configs_id'), 'embedding_provider_configs', ['id'], unique=False)
        op.create_index(op.f('ix_embedding_provider_configs_is_deleted'), 'embedding_provider_configs', ['is_deleted'], unique=False)
    
    # Check if workspace_embedding_settings table exists
    result = connection.execute(text("""
        SELECT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE table_name = 'workspace_embedding_settings'
        );
    """))
    workspace_table_exists = result.scalar()
    
    if not workspace_table_exists:
        # Recreate the workspace_embedding_settings table
        op.create_table('workspace_embedding_settings',
        sa.Column('workspace_id', sa.String(), nullable=False),
        sa.Column('auto_rotate', sa.Boolean(), nullable=False),
        sa.Column('fallback_provider_id', sa.String(), nullable=True),
        sa.Column('batch_size', sa.Integer(), nullable=False),
        sa.Column('retry_attempts', sa.Integer(), nullable=False),
        sa.Column('timeout', sa.Integer(), nullable=False),
        sa.Column('enable_caching', sa.Boolean(), nullable=False),
        sa.Column('cache_ttl', sa.Integer(), nullable=False),
        sa.Column('enable_monitoring', sa.Boolean(), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['fallback_provider_id'], ['embedding_provider_configs.id'], name=op.f('fk_workspace_embedding_settings_fallback_provider_id_embedding_provider_configs')),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_embedding_settings_workspace_id_workspaces')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_embedding_settings')),
        sa.UniqueConstraint('workspace_id', name=op.f('uq_workspace_embedding_settings_workspace_id'))
    )
    
        # Create indexes for workspace_embedding_settings
        op.create_index('idx_workspace_embedding_settings_workspace_id', 'workspace_embedding_settings', ['workspace_id'], unique=False)
        op.create_index(op.f('ix_workspace_embedding_settings_id'), 'workspace_embedding_settings', ['id'], unique=False)
        op.create_index(op.f('ix_workspace_embedding_settings_is_deleted'), 'workspace_embedding_settings', ['is_deleted'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop the new tables
    op.drop_table('workspace_embedding_settings')
    op.drop_table('embedding_provider_configs')
    
    # Drop the new enum type
    op.execute(text("DROP TYPE IF EXISTS embeddingprovidertype CASCADE"))
    
    # Note: This rollback just cleans up the new structure
    # The old table structure would need to be recreated if rollback is needed
    
    # ### end Alembic commands ###
