"""add_category_to_folders

Revision ID: 872a740bc11d
Revises: e8d306f638d4
Create Date: 2025-08-31 22:17:54.063182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '872a740bc11d'
down_revision = 'e8d306f638d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    foldercategory_enum = sa.Enum('FILES', 'NOTES', name='foldercategory')
    foldercategory_enum.create(op.get_bind())
    
    # Add the column with the enum type
    op.add_column('folders', sa.Column('category', foldercategory_enum, nullable=False, server_default='FILES'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('folders', 'category')
    # Drop the enum type
    sa.Enum(name='foldercategory').drop(op.get_bind())
    # ### end Alembic commands ###
