"""add_embedding_provider_configuration_tables

Revision ID: 9393b37a3104
Revises: 511c46b0ef5f
Create Date: 2025-09-03 22:34:28.714199

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9393b37a3104'
down_revision = '511c46b0ef5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_provider_configs',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider_type', sa.Enum('OPENAI', 'COHERE', 'HUGGINGFACE', 'LOCAL', name='embeddingprovidertype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ERROR', 'TESTING', name='embeddingproviderstatus'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('last_used', sa.String(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('average_latency', sa.Integer(), nullable=True),
    sa.Column('error_rate', sa.Integer(), nullable=True),
    sa.Column('total_tokens_processed', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_embedding_provider_configs_created_by_users')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_embedding_provider_configs_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embedding_provider_configs'))
    )
    op.create_index('idx_embedding_provider_configs_created_at', 'embedding_provider_configs', ['created_at'], unique=False)
    op.create_index('idx_embedding_provider_configs_is_active', 'embedding_provider_configs', ['is_active'], unique=False)
    op.create_index('idx_embedding_provider_configs_is_default', 'embedding_provider_configs', ['is_default'], unique=False)
    op.create_index('idx_embedding_provider_configs_provider_type', 'embedding_provider_configs', ['provider_type'], unique=False)
    op.create_index('idx_embedding_provider_configs_status', 'embedding_provider_configs', ['status'], unique=False)
    op.create_index('idx_embedding_provider_configs_workspace_id', 'embedding_provider_configs', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_embedding_provider_configs_id'), 'embedding_provider_configs', ['id'], unique=False)
    op.create_index(op.f('ix_embedding_provider_configs_is_deleted'), 'embedding_provider_configs', ['is_deleted'], unique=False)
    op.create_table('workspace_embedding_settings',
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('auto_rotate', sa.Boolean(), nullable=False),
    sa.Column('fallback_provider_id', sa.String(), nullable=True),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('retry_attempts', sa.Integer(), nullable=False),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('enable_caching', sa.Boolean(), nullable=False),
    sa.Column('cache_ttl', sa.Integer(), nullable=False),
    sa.Column('enable_monitoring', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['fallback_provider_id'], ['embedding_provider_configs.id'], name=op.f('fk_workspace_embedding_settings_fallback_provider_id_embedding_provider_configs')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_embedding_settings_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_embedding_settings')),
    sa.UniqueConstraint('workspace_id', name=op.f('uq_workspace_embedding_settings_workspace_id'))
    )
    op.create_index('idx_workspace_embedding_settings_workspace_id', 'workspace_embedding_settings', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_workspace_embedding_settings_id'), 'workspace_embedding_settings', ['id'], unique=False)
    op.create_index(op.f('ix_workspace_embedding_settings_is_deleted'), 'workspace_embedding_settings', ['is_deleted'], unique=False)
    op.alter_column('folders', 'category',
               existing_type=postgresql.ENUM('FILES', 'NOTES', name='foldercategory'),
               server_default=None,
               existing_nullable=False)
    # Update any non-numeric data to 0 before converting columns
    op.execute("UPDATE notes SET word_count = '0' WHERE word_count IS NULL OR word_count = '' OR word_count !~ '^[0-9]+$'")
    op.execute("UPDATE notes SET character_count = '0' WHERE character_count IS NULL OR character_count = '' OR character_count !~ '^[0-9]+$'")
    
    op.alter_column('notes', 'word_count',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               postgresql_using="word_count::integer",
               existing_nullable=False)
    op.alter_column('notes', 'character_count',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               postgresql_using="character_count::integer",
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'character_count',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('notes', 'word_count',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('folders', 'category',
               existing_type=postgresql.ENUM('FILES', 'NOTES', name='foldercategory'),
               server_default=sa.text("'FILES'::foldercategory"),
               existing_nullable=False)
    op.drop_index(op.f('ix_workspace_embedding_settings_is_deleted'), table_name='workspace_embedding_settings')
    op.drop_index(op.f('ix_workspace_embedding_settings_id'), table_name='workspace_embedding_settings')
    op.drop_index('idx_workspace_embedding_settings_workspace_id', table_name='workspace_embedding_settings')
    op.drop_table('workspace_embedding_settings')
    op.drop_index(op.f('ix_embedding_provider_configs_is_deleted'), table_name='embedding_provider_configs')
    op.drop_index(op.f('ix_embedding_provider_configs_id'), table_name='embedding_provider_configs')
    op.drop_index('idx_embedding_provider_configs_workspace_id', table_name='embedding_provider_configs')
    op.drop_index('idx_embedding_provider_configs_status', table_name='embedding_provider_configs')
    op.drop_index('idx_embedding_provider_configs_provider_type', table_name='embedding_provider_configs')
    op.drop_index('idx_embedding_provider_configs_is_default', table_name='embedding_provider_configs')
    op.drop_index('idx_embedding_provider_configs_is_active', table_name='embedding_provider_configs')
    op.drop_index('idx_embedding_provider_configs_created_at', table_name='embedding_provider_configs')
    op.drop_table('embedding_provider_configs')
    # ### end Alembic commands ###
