"""add_agent_type_and_update_agent_id_in_conversations

Revision ID: 94aa112ed09e
Revises: 712d778c66fc
Create Date: 2026-01-30 23:34:31.730255

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '94aa112ed09e'
down_revision = '712d778c66fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strapi_database_schema')
    op.drop_table('strapi_migrations')
    op.alter_column('agent_templates', 'is_public',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('agent_templates', 'usage_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('agent_templates', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('agents', 'agent_type',
               existing_type=postgresql.ENUM('default-agent', 'user-agent', name='agenttype'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('agents', 'is_built_in',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('agents', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'INACTIVE', 'DRAFT', 'ARCHIVED', name='agentstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('agents', 'is_public',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('agents', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('agents', 'ai_model',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=False)
    op.alter_column('agents', 'temperature',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.alter_column('agents', 'conversation_starters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('agents', 'conversation_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('agents', 'message_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('agents', 'total_tokens_used',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('agents', 'version',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('agents', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_agents_agent_type', table_name='agents')
    op.drop_index('ix_agents_is_built_in', table_name='agents')
    op.alter_column('conversation_participants', 'role',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversation_participants', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversation_participants', 'is_muted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversation_participants', 'unread_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversation_participants', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    
    # Drop the foreign key constraint first (before modifying agent_id)
    op.drop_constraint('fk_conversations_agent_id_agents', 'conversations', type_='foreignkey')
    
    # Add agent_type column with default value
    op.add_column('conversations', sa.Column('agent_type', sa.String(length=20), server_default='built_in', nullable=False))
    
    # Update existing agent_id NULL values to 'default'
    op.execute("UPDATE conversations SET agent_id = 'default' WHERE agent_id IS NULL")
    
    # Now alter agent_id to be NOT NULL with default
    op.alter_column('conversations', 'agent_id',
               existing_type=sa.VARCHAR(),
               nullable=False,
               server_default='default')
    
    op.alter_column('conversations', 'type',
               existing_type=postgresql.ENUM('DIRECT', 'GROUP', 'AI_CHAT', name='conversationtype'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversations', 'is_private',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversations', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversations', 'is_pinned',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversations', 'message_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversations', 'participant_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversations', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('embedding_provider_configs', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('embedding_provider_configs', 'usage_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('embedding_provider_configs', 'total_tokens_processed',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('embedding_provider_configs', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.add_column('embedding_usage', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('embedding_usage', 'tokens_processed',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('embedding_usage', 'success',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('embedding_usage', 'used_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('embedding_usage', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_embedding_usage_workspace_id'), 'embedding_usage', ['workspace_id'], unique=False)
    op.drop_constraint('fk_embedding_usage_created_by_users', 'embedding_usage', type_='foreignkey')
    op.drop_constraint('fk_embedding_usage_workspace_id_workspaces', 'embedding_usage', type_='foreignkey')
    op.alter_column('files', 'processing_status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('files', 'is_public',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('files', 'is_pinned',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('files', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('files', 'version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('files', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_files_created_by', table_name='files')
    op.drop_index('ix_files_workspace_id', table_name='files')
    op.alter_column('folders', 'category',
               existing_type=postgresql.ENUM('FILES', 'NOTES', name='foldercategory'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('folders', 'level',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('folders', 'is_private',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('folders', 'is_pinned',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('folders', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('folders', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_folders_created_by', table_name='folders')
    op.drop_index('ix_folders_workspace_id', table_name='folders')
    op.alter_column('messages', 'type',
               existing_type=postgresql.ENUM('TEXT', 'IMAGE', 'FILE', 'SYSTEM', 'AI_RESPONSE', name='messagetype'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('messages', 'is_edited',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('messages', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('messages', 'is_pinned',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_messages_is_deleted', table_name='messages')
    op.alter_column('notes', 'format',
               existing_type=postgresql.ENUM('plain_text', 'markdown', 'html', 'rich_text', name='noteformat'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notes', 'word_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notes', 'character_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notes', 'is_published',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notes', 'is_template',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notes', 'is_pinned',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notes', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notes', 'is_public',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notes', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_notes_created_by', table_name='notes')
    op.drop_index('ix_notes_workspace_id', table_name='notes')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'language',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('workspace_embedding_settings', 'auto_rotate',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('workspace_embedding_settings', 'batch_size',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('workspace_embedding_settings', 'retry_attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('workspace_embedding_settings', 'timeout',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('workspace_embedding_settings', 'enable_caching',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('workspace_embedding_settings', 'cache_ttl',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('workspace_embedding_settings', 'enable_monitoring',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('workspace_embedding_settings', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('workspace_members', 'role',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('workspace_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('workspace_members', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('workspace_members', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_workspace_members_user_id', table_name='workspace_members')
    op.drop_index('ix_workspace_members_workspace_id', table_name='workspace_members')
    op.alter_column('workspaces', 'color',
               existing_type=sa.VARCHAR(length=7),
               server_default=None,
               existing_nullable=False)
    op.alter_column('workspaces', 'is_private',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('workspaces', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('workspaces', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('workspaces', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_workspaces_created_by', table_name='workspaces')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_workspaces_created_by', 'workspaces', ['created_by'], unique=False)
    op.alter_column('workspaces', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('workspaces', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('workspaces', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('workspaces', 'is_private',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('workspaces', 'color',
               existing_type=sa.VARCHAR(length=7),
               server_default=sa.text("'#3B82F6'::character varying"),
               existing_nullable=False)
    op.create_index('ix_workspace_members_workspace_id', 'workspace_members', ['workspace_id'], unique=False)
    op.create_index('ix_workspace_members_user_id', 'workspace_members', ['user_id'], unique=False)
    op.alter_column('workspace_members', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('workspace_members', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('workspace_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('workspace_members', 'role',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'member'::character varying"),
               existing_nullable=False)
    op.alter_column('workspace_embedding_settings', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('workspace_embedding_settings', 'enable_monitoring',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('workspace_embedding_settings', 'cache_ttl',
               existing_type=sa.INTEGER(),
               server_default=sa.text('3600'),
               existing_nullable=False)
    op.alter_column('workspace_embedding_settings', 'enable_caching',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('workspace_embedding_settings', 'timeout',
               existing_type=sa.INTEGER(),
               server_default=sa.text('30000'),
               existing_nullable=False)
    op.alter_column('workspace_embedding_settings', 'retry_attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('3'),
               existing_nullable=False)
    op.alter_column('workspace_embedding_settings', 'batch_size',
               existing_type=sa.INTEGER(),
               server_default=sa.text('100'),
               existing_nullable=False)
    op.alter_column('workspace_embedding_settings', 'auto_rotate',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'language',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'en'::character varying"),
               existing_nullable=False)
    op.alter_column('users', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'UTC'::character varying"),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'user'::character varying"),
               existing_nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.create_index('ix_notes_workspace_id', 'notes', ['workspace_id'], unique=False)
    op.create_index('ix_notes_created_by', 'notes', ['created_by'], unique=False)
    op.alter_column('notes', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('notes', 'is_public',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('notes', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('notes', 'is_pinned',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('notes', 'is_template',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('notes', 'is_published',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('notes', 'character_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('notes', 'word_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('notes', 'format',
               existing_type=postgresql.ENUM('plain_text', 'markdown', 'html', 'rich_text', name='noteformat'),
               server_default=sa.text("'markdown'::noteformat"),
               existing_nullable=False)
    op.create_index('ix_messages_is_deleted', 'messages', ['is_deleted'], unique=False)
    op.alter_column('messages', 'is_pinned',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('messages', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('messages', 'is_edited',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('messages', 'type',
               existing_type=postgresql.ENUM('TEXT', 'IMAGE', 'FILE', 'SYSTEM', 'AI_RESPONSE', name='messagetype'),
               server_default=sa.text("'TEXT'::messagetype"),
               existing_nullable=False)
    op.create_index('ix_folders_workspace_id', 'folders', ['workspace_id'], unique=False)
    op.create_index('ix_folders_created_by', 'folders', ['created_by'], unique=False)
    op.alter_column('folders', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('folders', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('folders', 'is_pinned',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('folders', 'is_private',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('folders', 'level',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('folders', 'category',
               existing_type=postgresql.ENUM('FILES', 'NOTES', name='foldercategory'),
               server_default=sa.text("'FILES'::foldercategory"),
               existing_nullable=False)
    op.create_index('ix_files_workspace_id', 'files', ['workspace_id'], unique=False)
    op.create_index('ix_files_created_by', 'files', ['created_by'], unique=False)
    op.alter_column('files', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('files', 'version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('files', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('files', 'is_pinned',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('files', 'is_public',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('files', 'processing_status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.create_foreign_key('fk_embedding_usage_workspace_id_workspaces', 'embedding_usage', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key('fk_embedding_usage_created_by_users', 'embedding_usage', 'users', ['created_by'], ['id'])
    op.drop_index(op.f('ix_embedding_usage_workspace_id'), table_name='embedding_usage')
    op.alter_column('embedding_usage', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('embedding_usage', 'used_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('embedding_usage', 'success',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('embedding_usage', 'tokens_processed',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_column('embedding_usage', 'updated_by')
    op.alter_column('embedding_provider_configs', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('embedding_provider_configs', 'total_tokens_processed',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('embedding_provider_configs', 'usage_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('embedding_provider_configs', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.create_foreign_key('fk_conversations_agent_id_agents', 'conversations', 'agents', ['agent_id'], ['id'])
    op.alter_column('conversations', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('conversations', 'participant_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('conversations', 'message_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('conversations', 'agent_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('conversations', 'is_pinned',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('conversations', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('conversations', 'is_private',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('conversations', 'type',
               existing_type=postgresql.ENUM('DIRECT', 'GROUP', 'AI_CHAT', name='conversationtype'),
               server_default=sa.text("'DIRECT'::conversationtype"),
               existing_nullable=False)
    op.drop_column('conversations', 'agent_type')
    op.alter_column('conversation_participants', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('conversation_participants', 'unread_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('conversation_participants', 'is_muted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('conversation_participants', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('conversation_participants', 'role',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'participant'::character varying"),
               existing_nullable=False)
    op.create_index('ix_agents_is_built_in', 'agents', ['is_built_in'], unique=False)
    op.create_index('ix_agents_agent_type', 'agents', ['agent_type'], unique=False)
    op.alter_column('agents', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('agents', 'version',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'1.0.0'::character varying"),
               existing_nullable=False)
    op.alter_column('agents', 'total_tokens_used',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('agents', 'message_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('agents', 'conversation_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('agents', 'conversation_starters',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('agents', 'temperature',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'0.7'::character varying"),
               existing_nullable=False)
    op.alter_column('agents', 'ai_model',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'gpt-4'::character varying"),
               existing_nullable=False)
    op.alter_column('agents', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('agents', 'is_public',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('agents', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'INACTIVE', 'DRAFT', 'ARCHIVED', name='agentstatus'),
               server_default=sa.text("'ACTIVE'::agentstatus"),
               existing_nullable=False)
    op.alter_column('agents', 'is_built_in',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('agents', 'agent_type',
               existing_type=postgresql.ENUM('default-agent', 'user-agent', name='agenttype'),
               server_default=sa.text("'user-agent'::agenttype"),
               existing_nullable=False)
    op.alter_column('agent_templates', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('agent_templates', 'usage_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('agent_templates', 'is_public',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.create_table('strapi_migrations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='strapi_migrations_pkey')
    )
    op.create_table('strapi_database_schema',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('schema', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='strapi_database_schema_pkey')
    )
    # ### end Alembic commands ###
