"""remove_redundant_status_and_isdefault_fields

Revision ID: bdccb64add5b
Revises: 9393b37a3104
Create Date: 2025-09-13 00:00:07.919495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bdccb64add5b'
down_revision = '9393b37a3104'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_embedding_provider_configs_is_default', table_name='embedding_provider_configs')
    op.drop_index('idx_embedding_provider_configs_status', table_name='embedding_provider_configs')
    op.drop_column('embedding_provider_configs', 'status')
    op.drop_column('embedding_provider_configs', 'is_default')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embedding_provider_configs', sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('embedding_provider_configs', sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', 'ERROR', 'TESTING', name='embeddingproviderstatus'), autoincrement=False, nullable=False))
    op.create_index('idx_embedding_provider_configs_status', 'embedding_provider_configs', ['status'], unique=False)
    op.create_index('idx_embedding_provider_configs_is_default', 'embedding_provider_configs', ['is_default'], unique=False)
    # ### end Alembic commands ###
