"""add_knowledge_base_folders

Revision ID: e8d306f638d4
Revises: 9e80a0f6aa32
Create Date: 2025-08-31 15:33:53.041262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8d306f638d4'
down_revision = '9e80a0f6aa32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
