"""add_agent_models_and_conversation_agent_integration

Revision ID: fa1f7cb80f36
Revises: a87e5993cbc0
Create Date: 2025-10-26 22:39:49.882022

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fa1f7cb80f36'
down_revision = 'a87e5993cbc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_templates',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('template_config', sa.JSON(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_agent_templates_created_by_users')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_agent_templates_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_templates'))
    )
    op.create_index(op.f('ix_agent_templates_id'), 'agent_templates', ['id'], unique=False)
    op.create_index(op.f('ix_agent_templates_is_deleted'), 'agent_templates', ['is_deleted'], unique=False)
    op.create_table('agents',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DRAFT', 'ARCHIVED', name='agentstatus'), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('ai_model', sa.String(length=100), nullable=False),
    sa.Column('temperature', sa.String(length=10), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('tools', sa.JSON(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('conversation_count', sa.Integer(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('total_tokens_used', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('parent_agent_id', sa.String(), nullable=True),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_agents_created_by_users')),
    sa.ForeignKeyConstraint(['parent_agent_id'], ['agents.id'], name=op.f('fk_agents_parent_agent_id_agents')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_agents_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents'))
    )
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    op.create_index(op.f('ix_agents_is_deleted'), 'agents', ['is_deleted'], unique=False)
    op.add_column('conversations', sa.Column('agent_id', sa.String(), nullable=True))
    op.create_foreign_key(op.f('fk_conversations_agent_id_agents'), 'conversations', 'agents', ['agent_id'], ['id'])
    op.alter_column('embedding_usage', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('embedding_usage', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('embedding_usage', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_embedding_usage_created_by'), 'embedding_usage', ['created_by'], unique=False)
    op.create_index(op.f('ix_embedding_usage_id'), 'embedding_usage', ['id'], unique=False)
    op.create_index(op.f('ix_embedding_usage_workspace_id'), 'embedding_usage', ['workspace_id'], unique=False)
    op.drop_constraint('fk_embedding_usage_created_by_users', 'embedding_usage', type_='foreignkey')
    op.drop_constraint('fk_embedding_usage_workspace_id_workspaces', 'embedding_usage', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_embedding_usage_workspace_id_workspaces', 'embedding_usage', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key('fk_embedding_usage_created_by_users', 'embedding_usage', 'users', ['created_by'], ['id'])
    op.drop_index(op.f('ix_embedding_usage_workspace_id'), table_name='embedding_usage')
    op.drop_index(op.f('ix_embedding_usage_id'), table_name='embedding_usage')
    op.drop_index(op.f('ix_embedding_usage_created_by'), table_name='embedding_usage')
    op.alter_column('embedding_usage', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('embedding_usage', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('embedding_usage', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('fk_conversations_agent_id_agents'), 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'agent_id')
    op.drop_index(op.f('ix_agents_is_deleted'), table_name='agents')
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_agent_templates_is_deleted'), table_name='agent_templates')
    op.drop_index(op.f('ix_agent_templates_id'), table_name='agent_templates')
    op.drop_table('agent_templates')
    # ### end Alembic commands ###
